---
apiVersion: v1
kind: Service
metadata:
  name: api-route
spec:
  type: LoadBalancer
  selector:
    app: api-route
  ports:
    - name: api-route
      port: 8081
      targetPort: 8080
 