apiVersion: apps/v1
kind: CronJob
metadata:
  name: job2-schedule
spec:
  schedule: "0 12 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: job2-schedule
              image: job2
              imagePullPolicy: IfNotPresent
              restartPolicy: OnFailure
