apiVersion: apps/v1
kind: CronJob
metadata:
  name: job1-schedule
spec:
  schedule: "0 12 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: job1-schedule
              image: job1
              imagePullPolicy: IfNotPresent
              restartPolicy: OnFailure
